###
POST http://localhost:5000/upload_csv
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="coordenates.csv"
Content-Type: text/csv

@./coordenates.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--
